---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-obj3
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/mysql"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: pv-apachephp
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /u01/app/oracle/phpapp
  storageClassName: manual
...
