apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql
  namespace: ns-phpmysql
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
  volumeMode: Filesystem
  volumeName: pv-mysql
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 20Gi
...
