---
apiVersion: v1
kind: Service
metadata:
  name: svc-apache-clusterip-select
  namespace: ns-phpmysql
spec:
  selector:
    app: apache-select
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: svc-apache-nodeport-select
  namespace: ns-phpmysql
spec:
  selector:
    app: apache-select
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
    nodePort: 31113
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: svc-apache-clusterip-insert
  namespace: ns-phpmysql
spec:
  selector:
    app: apache-insert
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: svc-apache-nodeport-insert
  namespace: ns-phpmysql
spec:
  selector:
    app: apache-insert
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
    nodePort: 31114
  type: NodePort

...
